"""Core modules for cli-anything-starrail."""

from .session import Session
from .project import (
    Project,
    TaskConfig,
    EmulatorConfig,
    DungeonConfig,
    RogueConfig,
    WeeklyConfig,
    OrnamentConfig,
    create_project,
    load_project,
    save_project,
    load_src_config,
    project_from_src_config,
    save_as_src_config,
    project_to_src_config,
)
from .task import TaskRunner, TaskStatus, TaskResult
from .version import (
    VersionInfo,
    get_src_version,
    check_compatibility,
    CompatibilityReport,
    get_repo_root,
)
from .mapping import (
    EMULATOR_MAPPINGS,
    DUNGEON_MAPPINGS,
    ROGUE_MAPPINGS,
    WEEKLY_MAPPINGS,
    ORNAMENT_MAPPINGS,
    TASK_METHOD_MAPPINGS,
    DEFAULT_TASKS,
    CONFIG_SCHEMA_VERSION,
    normalize_task_name,
    get_task_method,
)

__all__ = [
    "Session",
    "Project",
    "TaskConfig",
    "EmulatorConfig",
    "DungeonConfig",
    "RogueConfig",
    "WeeklyConfig",
    "OrnamentConfig",
    "create_project",
    "load_project",
    "save_project",
    "load_src_config",
    "project_from_src_config",
    "save_as_src_config",
    "project_to_src_config",
    "TaskRunner",
    "TaskStatus",
    "TaskResult",
    "VersionInfo",
    "get_src_version",
    "check_compatibility",
    "CompatibilityReport",
    "get_repo_root",
    "EMULATOR_MAPPINGS",
    "DUNGEON_MAPPINGS",
    "ROGUE_MAPPINGS",
    "WEEKLY_MAPPINGS",
    "ORNAMENT_MAPPINGS",
    "TASK_METHOD_MAPPINGS",
    "DEFAULT_TASKS",
    "CONFIG_SCHEMA_VERSION",
    "normalize_task_name",
    "get_task_method",
]
